title: Time to make
hero_image: images/banner.png
description: A spinning wheel that reveals random prompts
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Motor wiring
  - title: Code
  - title: Add switch and pressed
  - title: Add LEDs
  - title: Make chooser
  - title: Make dial and dial text
  - title: Attach everythng to box
  - title: Challange - random angle choice
    completion:
      - engaged      
  - title: More challenges
    challenge: true
    completion:
      - external
